In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("final.csv")
df

,instructor,instructor_first_name,course,course_name,num_excellence_awards,num_outstanding_awards,uiuc_award,national_award,rmp_num_reviews,rmp_rating,...,D-,F,term,num_sections,gened,num_semesters,num_students,avg_gpa,total_faculty_awards,teaching_next_semester
0,Kang,Yoonjung,AAS 100: Intro Asian American Studies,Intro Asian American Studies,0.0,0.0,[],[],0.0,NaN,...,0.000000,0.040000,"['fa2018', 'fa2019', 'fa2020', 'sp2018', 'sp20...",12.0,"Social & Beh Sci - Soc Sci, Cultural Studies -...",8,50.0,3.374000,0,False
1,Shin,Jeongsu,AAS 100: Intro Asian American Studies,Intro Asian American Studies,0.0,0.0,[],[],0.0,NaN,...,0.000000,0.021277,"['fa2022', 'sp2023']",4.0,"Social & Beh Sci - Soc Sci, Cultural Studies -...",2,94.0,3.737979,0,False
2,Guruparan,Akil,AAS 100: Intro Asian American Studies,Intro Asian American Studies,0.0,0.0,[],[],0.0,NaN,...,0.000000,0.020408,"['fa2020', 'sp2021', 'sp2024']",6.0,"Social & Beh Sci - Soc Sci, Cultural Studies -...",3,98.0,3.527959,0,False
3,Kim,Gabriel,AAS 100: Intro Asian American Studies,Intro Asian American Studies,0.0,0.0,[],[],0.0,NaN,...,0.000000,0.020833,"['fa2024', 'sp2025', 'fa2025']",2.0,"Social & Beh Sci - Soc Sci, Cultural Studies -...",1,48.0,3.653125,0,True
4,Espiritu,Augusto,AAS 100: Intro Asian American Studies,Intro Asian American Studies,1.0,1.0,[],[],17.0,3.8,...,0.013216,0.039648,"['fa2023', 'sp2019', 'sp2020', 'fa2017']",18.0,"Social & Beh Sci - Soc Sci, Cultural Studies -...",4,227.0,3.300044,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8304,McCoy,Annette,VM 656: Large Animal Medicine and Surgery III,Large Animal Medicine and Surgery III,17.0,10.0,[],[],0.0,NaN,...,0.000000,0.000000,"['sp2022', 'sp2023', 'sp2024', 'sp2025']",6.0,NaN,3,770.0,2.893506,0,False
8305,Wilkins,Pamela,VM 656: Large Animal Medicine and Surgery III,Large Animal Medicine and Surgery III,4.0,0.0,[],[],0.0,NaN,...,0.000000,0.000000,"['sp2022', 'sp2023', 'sp2024', 'sp2025']",6.0,NaN,3,770.0,2.893506,0,False
8306,Gutierrez Nibeyro,Santiago,VM 656: Large Animal Medicine and Surgery III,Large Animal Medicine and Surgery III,9.0,6.0,[],[],0.0,NaN,...,0.000000,0.000000,"['sp2022', 'sp2023', 'sp2024', 'sp2025']",6.0,NaN,3,770.0,2.893506,0,False
8307,French,Dennis,VM 656: Large Animal Medicine and Surgery III,Large Animal Medicine and Surgery III,7.0,0.0,[],[],0.0,NaN,...,0.000000,0.000000,"['sp2022', 'sp2023', 'sp2024', 'sp2025']",6.0,NaN,3,770.0,2.893506,0,False
8308,Stewart,Matthew,VM 656: Large Animal Medicine and Surgery III,Large Animal Medicine and Surgery III,0.0,0.0,[],[],0.0,NaN,...,0.000000,0.000000,"['sp2022', 'sp2023', 'sp2024', 'sp2025']",6.0,NaN,3,770.0,2.893506,0,False

In [7]:
df.columns

Index(['instructor', 'instructor_first_name', 'course', 'course_name',
       'num_excellence_awards', 'num_outstanding_awards', 'uiuc_award',
       'national_award', 'rmp_num_reviews', 'rmp_rating', 'A+', 'A', 'A-',
       'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D', 'D-', 'F', 'term',
       'num_sections', 'gened', 'num_semesters', 'num_students', 'avg_gpa',
       'total_faculty_awards', 'teaching_next_semester'],
      dtype='object')

In [14]:
subjects = df.course.str.split(" ").str[0].unique()
subjects

print("var ALL_SUBJECTS = [\"" + "\",\"".join(subjects) + "\"]")

var ALL_SUBJECTS = ["AAS","ABE","ACCY","ACE","ACES","ADV","AE","AFRO","AFST","AGCM","AGED","AHS","AIS","ALEC","ANSC","ANTH","ARAB","ARCH","ART","ARTD","ARTE","ARTF","ARTH","ARTJ","ARTS","ASRM","ASTR","ATMS","BADM","BCOG","BCS","BDI","BIOC","BIOE","BIOP","BTW","BUS","CEE","CHBE","CHEM","CHIN","CHLH","CHP","CI","CLCV","CMN","CPSC","CS","CW","CWL","DANC","DTX","EALC","ECE","ECON","EDUC","EIL","ENG","ENGL","ENSU","ENVS","EOL","EPOL","EPS","EPSY","ERAM","ESE","ETMA","EURO","FAA","FIN","FR","FSHN","GEOG","GEOL","GER","GGIS","GLBL","GS","GSD","GWS","HDFS","HIST","HK","HORT","HRD","IB","IE","IHLT","INFO","IS","ITAL","JAPN","JOUR","KIN","KOR","LA","LAS","LAST","LAW","LEAD","LER","LING","LLS","MACS","MATH","MBA","MCB","MDIA","ME","MILS","MSE","MUS","MUSC","MUSE","NE","NPRE","NRES","NUTR","PATH","PHIL","PHYS","PLPA","POL","PORT","PS","PSM","PSYC","REHB","REL","RHET","RSOC","RST","RUSS","SBC","SCAN","SE","SHS","SLAV","SLCL","SOC","SOCW","SPAN","SPED","STAT","TAM","TE","THEA","TRST","TSM","UKR","UP","VCM","VM"]

In [6]:
print('<datalist id="depts">')
for subject in subjects:
  print(f'  <option value="{subject}"></option>')
print('</datalist>')

<datalist id="depts">
  <option value="AAS"></option>
  <option value="ABE"></option>
  <option value="ACCY"></option>
  <option value="ACE"></option>
  <option value="ACES"></option>
  <option value="ADV"></option>
  <option value="AE"></option>
  <option value="AFRO"></option>
  <option value="AFST"></option>
  <option value="AGCM"></option>
  <option value="AGED"></option>
  <option value="AHS"></option>
  <option value="AIS"></option>
  <option value="ALEC"></option>
  <option value="ANSC"></option>
  <option value="ANTH"></option>
  <option value="ARAB"></option>
  <option value="ARCH"></option>
  <option value="ART"></option>
  <option value="ARTD"></option>
  <option value="ARTE"></option>
  <option value="ARTF"></option>
  <option value="ARTH"></option>
  <option value="ARTJ"></option>
  <option value="ARTS"></option>
  <option value="ASRM"></option>
  <option value="ASTR"></option>
  <option value="ATMS"></option>
  <option value="BADM"></option>
  <option value="BCOG"></option>
  <option value="BCS"></option>
  <option value="BDI"></option>
  <option value="BIOC"></option>
  <option value="BIOE"></option>
  <option value="BIOP"></option>
  <option value="BTW"></option>
  <option value="BUS"></option>
  <option value="CEE"></option>
  <option value="CHBE"></option>
  <option value="CHEM"></option>
  <option value="CHIN"></option>
  <option value="CHLH"></option>
  <option value="CHP"></option>
  <option value="CI"></option>
  <option value="CLCV"></option>
  <option value="CMN"></option>
  <option value="CPSC"></option>
  <option value="CS"></option>
  <option value="CW"></option>
  <option value="CWL"></option>
  <option value="DANC"></option>
  <option value="DTX"></option>
  <option value="EALC"></option>
  <option value="ECE"></option>
  <option value="ECON"></option>
  <option value="EDUC"></option>
  <option value="EIL"></option>
  <option value="ENG"></option>
  <option value="ENGL"></option>
  <option value="ENSU"></option>
  <option value="ENVS"></option>
  <option value="EOL"></option>
  <option value="EPOL"></option>
  <option value="EPS"></option>
  <option value="EPSY"></option>
  <option value="ERAM"></option>
  <option value="ESE"></option>
  <option value="ETMA"></option>
  <option value="EURO"></option>
  <option value="FAA"></option>
  <option value="FIN"></option>
  <option value="FR"></option>
  <option value="FSHN"></option>
  <option value="GEOG"></option>
  <option value="GEOL"></option>
  <option value="GER"></option>
  <option value="GGIS"></option>
  <option value="GLBL"></option>
  <option value="GS"></option>
  <option value="GSD"></option>
  <option value="GWS"></option>
  <option value="HDFS"></option>
  <option value="HIST"></option>
  <option value="HK"></option>
  <option value="HORT"></option>
  <option value="HRD"></option>
  <option value="IB"></option>
  <option value="IE"></option>
  <option value="IHLT"></option>
  <option value="INFO"></option>
  <option value="IS"></option>
  <option value="ITAL"></option>
  <option value="JAPN"></option>
  <option value="JOUR"></option>
  <option value="KIN"></option>
  <option value="KOR"></option>
  <option value="LA"></option>
  <option value="LAS"></option>
  <option value="LAST"></option>
  <option value="LAW"></option>
  <option value="LEAD"></option>
  <option value="LER"></option>
  <option value="LING"></option>
  <option value="LLS"></option>
  <option value="MACS"></option>
  <option value="MATH"></option>
  <option value="MBA"></option>
  <option value="MCB"></option>
  <option value="MDIA"></option>
  <option value="ME"></option>
  <option value="MILS"></option>
  <option value="MSE"></option>
  <option value="MUS"></option>
  <option value="MUSC"></option>
  <option value="MUSE"></option>
  <option value="NE"></option>
  <option value="NPRE"></option>
  <option value="NRES"></option>
  <option value="NUTR"></option>
  <option value="PATH"></option>
  <option value="PHIL"></option>
  <option value="PHYS"></option>
  <option value="PLPA"></option>
  <option value="POL"></option>
  <option value="PORT"></option>
  <option value="PS"></option>
  <option value="PSM"></option>
  <option value="PSYC"></option>
  <option value="REHB"></option>
  <option value="REL"></option>
  <option value="RHET"></option>
  <option value="RSOC"></option>
  <option value="RST"></option>
  <option value="RUSS"></option>
  <option value="SBC"></option>
  <option value="SCAN"></option>
  <option value="SE"></option>
  <option value="SHS"></option>
  <option value="SLAV"></option>
  <option value="SLCL"></option>
  <option value="SOC"></option>
  <option value="SOCW"></option>
  <option value="SPAN"></option>
  <option value="SPED"></option>
  <option value="STAT"></option>
  <option value="TAM"></option>
  <option value="TE"></option>
  <option value="THEA"></option>
  <option value="TRST"></option>
  <option value="TSM"></option>
  <option value="UKR"></option>
  <option value="UP"></option>
  <option value="VCM"></option>
  <option value="VM"></option>
</datalist>

In [14]:
df["national_award"].unique()

array(['[]', "['National Academy of Sciences']",
       "['National Academy of Engineering']"], dtype=object)